#!/bin/sh
if [ -z "$1" ]; then
	echo "No Branch Specified. Please Specify a Branch"
	echo "Example: syncb dev-branch"
else
	while read line; do
		if [ ! -z "$line" ] && [[ ${line::1} != "#" ]]; then
			echo "Syncing $line $1..."
			cd $line
			git status
			isGitRepo="$?"
			if [[ $isGitRepo != "0" ]]; then
				echo "$line is not a git repository"
			else
				git stash
				git checkout $1
				checkoutSuccess="$?"
				if [[ $checkoutSuccess != "0" ]]; then
					echo "Failed to checkout branch $1"
				else
					git fetch upstream
					git pull upstream $1
					git push -u origin $1 --no-verify
				fi
				git stash pop
				echo "$line $1 - Sync Complete"
			fi
		fi
	done < ./projects
	echo "Synced $1 for all projects" 
fi
